### ISSUE TITLE
Does not work with Puppet 3.5.1 (Hiera 1.3.2)

### ISSUE THREAD

**Issue by justicel** [voxpupuli/hiera-eyaml#89]
```
/etc/puppet# hiera secrets
/var/lib/gems/1.9.1/gems/hiera-eyaml-2.0.1/lib/hiera/backend/eyaml_backend.rb:19:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.1/gems/hiera-1.3.2/lib/hiera/backend.rb:172:in `new'
    from /var/lib/gems/1.9.1/gems/hiera-1.3.2/lib/hiera/backend.rb:172:in `block in lookup'
    from /var/lib/gems/1.9.1/gems/hiera-1.3.2/lib/hiera/backend.rb:170:in `each'
    from /var/lib/gems/1.9.1/gems/hiera-1.3.2/lib/hiera/backend.rb:170:in `lookup'
    from /var/lib/gems/1.9.1/gems/hiera-1.3.2/lib/hiera.rb:60:in `lookup'
    from /var/lib/gems/1.9.1/gems/hiera-1.3.2/bin/hiera:221:in `<top (required)>'
    from /usr/local/bin/hiera:19:in `load'
    from /usr/local/bin/hiera:19:in `<main>'
```

That's the error I receive when trying to simply list a hash. Let me know if you need anything else!
